# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/131DJcWg2uY4cJeTmMe2to8MaRpqIXdPJ
"""

import streamlit as st
import numpy as np
import pandas as pd
import pickle
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.sequence import pad_sequences
import shap
from lime.lime_text import LimeTextExplainer
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import scipy.sparse as sp

# Page config
st.set_page_config(
    page_title="Job Posting Fraud Detector",
    page_icon="🔍",
    layout="wide"
)

# Custom CSS for better styling
st.markdown("""
    <style>
    .main-header {
        font-size: 3rem;
        font-weight: bold;
        text-align: center;
        color: #1f77b4;
        margin-bottom: 2rem;
    }
    .fraud-metric {
        background-color: #ffebee;
        padding: 20px;
        border-radius: 10px;
        border-left: 5px solid #f44336;
    }
    .legit-metric {
        background-color: #e8f5e9;
        padding: 20px;
        border-radius: 10px;
        border-left: 5px solid #4caf50;
    }
    .highlight-word {
        padding: 2px 5px;
        border-radius: 3px;
        margin: 2px;
    }
    .fraud-word {
        background-color: #ffcdd2;
        color: #c62828;
    }
    .legit-word {
        background-color: #c8e6c9;
        color: #2e7d32;
    }
    </style>
""", unsafe_allow_html=True)

# ============= LOAD MODELS (cached) =============
@st.cache_resource
def load_models():
    """Load all models and preprocessing objects"""
    try:
        # Load models
        nb_model = pickle.load(open('models/nb_model.pkl', 'rb'))
        lstm_model = load_model('models/lstm_model.h5')
        vectorizer = pickle.load(open('models/tfidf_vectorizer.pkl', 'rb'))
        tokenizer = pickle.load(open('models/tokenizer.pkl', 'rb'))

        # Initialize NLTK
        nltk.download('punkt', quiet=True)
        nltk.download('stopwords', quiet=True)
        nltk.download('wordnet', quiet=True)

        return nb_model, lstm_model, vectorizer, tokenizer
    except Exception as e:
        st.error(f"Error loading models: {e}")
        return None, None, None, None

# Load models
nb_model, lstm_model, vectorizer, tokenizer = load_models()

# ============= HELPER FUNCTIONS (from your notebook) =============
# TODO: Your teammate should copy the InterpretableEnsemble class here
# For now, I'll create placeholder functions

def preprocess_text(text):
    """Preprocess text for model input"""
    # TODO: Copy your preprocessing logic from notebook
    return text.lower().strip()

def get_prediction(text):
    """
    Get fraud prediction with full explanation
    TODO: Your teammate should integrate the InterpretableEnsemble.predict_with_explanation() here
    """
    # Placeholder - replace with actual ensemble prediction
    return {
        'fraud_probability': 0.85,
        'fraud_probability_pct': '85.0%',
        'risk_level': 'HIGH RISK',
        'risk_icon': '🔴',
        'ensemble_decision': 'FRAUD',
        'confidence': 'HIGH',
        'individual_predictions': {
            'naive_bayes_score': 0.41,
            'lstm_score': 0.96,
            'boost_details': [
                "🚩 No company logo (+5%)",
                "🚩 No screening questions (+5%)",
                "🚩 Urgency language: asap, needed (+8%)"
            ],
            'total_boost': 0.18
        },
        'explanation': {
            'patterns': {
                'urgency_indicators': {'present': True, 'examples': ['asap', 'immediately']},
                'payment_requests': {'present': False, 'examples': []},
                'vague_language': {'present': True, 'examples': ['flexible']}
            }
        }
    }

def get_shap_explanation(text):
    """
    Get SHAP explanation for Naive Bayes
    TODO: Copy shap_explain_nb_for_text() from notebook
    """
    # Placeholder
    return [
        ('urgent', 0.0841),
        ('immediately', 0.0623),
        ('experience', -0.0412),
        ('manager', -0.0387)
    ]

def get_lime_explanation(text):
    """
    Get LIME explanation for LSTM
    TODO: Your teammate implements this with lime_explain_lstm_for_text()
    """
    # Placeholder
    return {
        'word_contributions': [
            ('asap', 0.2841),
            ('needed', 0.1923),
            ('phone', 0.1456),
            ('customer', -0.0234)
        ],
        'html_visualization': '<div>LIME visualization will go here</div>'
    }

# ============= MAIN APP =============
def main():
    # Header
    st.markdown('<p class="main-header">🔍 Job Posting Fraud Detector</p>', unsafe_allow_html=True)
    st.markdown("**Powered by Ensemble ML + SHAP + LIME Interpretability**")
    st.markdown("---")

    # Sidebar
    with st.sidebar:
        st.header("📋 About")
        st.write("""
        This tool uses an ensemble of machine learning models to detect fraudulent job postings:

        **Models:**
        - Naive Bayes (TF-IDF features)
        - LSTM (Sequential patterns)
        - Rule-based pattern detection

        **Interpretability:**
        - SHAP for NB word importance
        - LIME for LSTM context analysis
        - Pattern-based red flags
        """)

        st.markdown("---")
        st.header("⚙️ Settings")
        show_technical = st.checkbox("Show technical details", value=True)
        show_shap = st.checkbox("Show SHAP analysis", value=True)
        show_lime = st.checkbox("Show LIME analysis", value=True)

    # Main content area
    col1, col2 = st.columns([2, 1])

    with col1:
        st.subheader("📝 Enter Job Posting")
        job_text = st.text_area(
            "Paste the job posting text here:",
            height=300,
            placeholder="Enter job title, description, requirements, company info, etc.",
            help="Include as much information as available from the job posting"
        )

        # Optional metadata
        with st.expander("➕ Additional Information (Optional)"):
            col_a, col_b = st.columns(2)
            with col_a:
                has_logo = st.selectbox("Has company logo?", ["Unknown", "Yes", "No"])
                has_questions = st.selectbox("Has screening questions?", ["Unknown", "Yes", "No"])
            with col_b:
                telecommuting = st.selectbox("Remote work?", ["Unknown", "Yes", "No"])
                salary_range = st.text_input("Salary range (if provided)")

        analyze_button = st.button("🔍 Analyze Job Posting", type="primary", use_container_width=True)

    with col2:
        st.subheader("📊 Example Job Postings")
        if st.button("Load Fraud Example"):
            job_text = "Customer service reps needed ASAP! Will explain on phone. Cash pay daily. No experience needed."
            st.rerun()

        if st.button("Load Legitimate Example"):
            job_text = "Senior Software Engineer at Google. 5+ years experience required. Competitive salary and benefits. Apply through careers.google.com."
            st.rerun()

    # Analysis results
    if analyze_button and job_text:
        st.markdown("---")
        st.header("🎯 Analysis Results")

        with st.spinner("Analyzing job posting..."):
            # Get prediction
            result = get_prediction(job_text)

            # ============= RESULTS SECTION =============

            # Overall prediction
            st.subheader("Overall Assessment")

            if result['fraud_probability'] >= 0.7:
                metric_class = "fraud-metric"
            elif result['fraud_probability'] >= 0.4:
                metric_class = "fraud-metric"  # Medium risk
            else:
                metric_class = "legit-metric"

            st.markdown(f"""
                <div class="{metric_class}">
                    <h2>{result['risk_icon']} {result['risk_level']}</h2>
                    <h1>{result['fraud_probability_pct']}</h1>
                    <p style="font-size: 1.2rem;">Fraud Probability</p>
                    <p><strong>Prediction:</strong> {result['ensemble_decision']}</p>
                    <p><strong>Confidence:</strong> {result['confidence']}</p>
                </div>
            """, unsafe_allow_html=True)

            st.markdown("---")

            # ============= MODEL BREAKDOWN =============
            st.subheader("🤖 Model Breakdown")

            nb_score = result['individual_predictions']['naive_bayes_score']
            lstm_score = result['individual_predictions']['lstm_score']
            base_prob = 0.25 * nb_score + 0.75 * lstm_score

            col1, col2, col3 = st.columns(3)

            with col1:
                st.metric(
                    "Naive Bayes",
                    f"{nb_score:.1%}",
                    help="TF-IDF word frequency analysis"
                )
                st.caption("Weight: 25%")
                st.caption(f"Contribution: {nb_score*0.25:.1%}")

            with col2:
                st.metric(
                    "LSTM",
                    f"{lstm_score:.1%}",
                    help="Sequential pattern detection"
                )
                st.caption("Weight: 75%")
                st.caption(f"Contribution: {lstm_score*0.75:.1%}")

            with col3:
                st.metric(
                    "Base Probability",
                    f"{base_prob:.1%}",
                    help="Weighted combination of models"
                )

            # ============= RULE-BASED ADJUSTMENTS =============
            if result['individual_predictions'].get('boost_details'):
                st.markdown("---")
                st.subheader("🚩 Rule-Based Adjustments")

                boost_details = result['individual_predictions']['boost_details']
                total_boost = result['individual_predictions'].get('total_boost', 0)

                for boost in boost_details:
                    st.warning(boost)

                st.info(f"**Total Boost:** +{total_boost*100:.1f}%")

                final_calc = base_prob + total_boost
                st.success(f"""
                    **Final Calculation:** {base_prob:.1%} (base) + {total_boost:.1%} (rules) = {final_calc:.1%}
                    {f" → Capped at 95.0%" if final_calc > 0.95 else ""}
                """)

            # ============= INTERPRETABILITY SECTION =============
            if show_technical:
                st.markdown("---")
                st.header("🔬 Interpretability Analysis")

                tab1, tab2, tab3 = st.tabs(["📊 SHAP (Naive Bayes)", "🔍 LIME (LSTM)", "🎯 Pattern Detection"])

                # TAB 1: SHAP
                with tab1:
                    if show_shap:
                        st.subheader("TF-IDF Feature Importance (SHAP)")
                        st.write("Shows which words/phrases influenced the Naive Bayes model's prediction:")

                        shap_features = get_shap_explanation(job_text)

                        # Create DataFrame for display
                        shap_df = pd.DataFrame(shap_features, columns=['Feature', 'SHAP Value'])
                        shap_df['Impact'] = shap_df['SHAP Value'].apply(
                            lambda x: '↑ Fraud' if x > 0 else '↓ Legitimate'
                        )
                        shap_df['Contribution %'] = shap_df['SHAP Value'].apply(lambda x: f"{x*100:+.2f}%")

                        # Display top fraud indicators
                        fraud_features = shap_df[shap_df['SHAP Value'] > 0].sort_values('SHAP Value', ascending=False)
                        legit_features = shap_df[shap_df['SHAP Value'] < 0].sort_values('SHAP Value')

                        col1, col2 = st.columns(2)
                        with col1:
                            st.markdown("**🔴 Fraud Indicators**")
                            if len(fraud_features) > 0:
                                for _, row in fraud_features.iterrows():
                                    st.markdown(f"- **{row['Feature']}**: {row['Contribution %']}")
                            else:
                                st.write("No significant fraud indicators found")

                        with col2:
                            st.markdown("**🟢 Legitimate Indicators**")
                            if len(legit_features) > 0:
                                for _, row in legit_features.head(5).iterrows():
                                    st.markdown(f"- **{row['Feature']}**: {row['Contribution %']}")
                            else:
                                st.write("No significant legitimate indicators found")

                        # Full table in expander
                        with st.expander("View full SHAP analysis"):
                            st.dataframe(shap_df, use_container_width=True)
                    else:
                        st.info("SHAP analysis disabled in settings")

                # TAB 2: LIME
                with tab2:
                    if show_lime:
                        st.subheader("Word-Level Explanation (LIME)")
                        st.write("Shows which words/phrases in context influenced the LSTM's prediction:")

                        # TODO: Your teammate implements this section
                        lime_result = get_lime_explanation(job_text)

                        # Display word contributions
                        st.markdown("**Top Word Contributions:**")
                        for word, contrib in lime_result['word_contributions']:
                            color = "🔴" if contrib > 0 else "🟢"
                            st.markdown(f"{color} **{word}**: {contrib*100:+.1f}% {'(fraud indicator)' if contrib > 0 else '(legitimate indicator)'}")

                        # Display LIME HTML visualization
                        st.markdown("---")
                        st.markdown("**Interactive Text Highlighting:**")
                        st.components.v1.html(lime_result['html_visualization'], height=400, scrolling=True)
                    else:
                        st.info("LIME analysis disabled in settings")

                # TAB 3: Pattern Detection
                with tab3:
                    st.subheader("Fraud Pattern Detection")
                    st.write("Rule-based detection of common fraud indicators:")

                    patterns = result['explanation']['patterns']

                    # Urgency indicators
                    if patterns['urgency_indicators']['present']:
                        st.error("**⚠️ Urgency Indicators Detected**")
                        st.write("Keywords:", ", ".join(patterns['urgency_indicators']['examples']))

                    # Payment requests
                    if patterns['payment_requests']['present']:
                        st.error("**💰 Payment Request Detected**")
                        st.write("Keywords:", ", ".join(patterns['payment_requests']['examples']))

                    # Vague language
                    if patterns['vague_language']['present']:
                        st.warning("**❓ Vague Language Detected**")
                        st.write("Keywords:", ", ".join(patterns['vague_language']['examples']))

                    if not any([patterns['urgency_indicators']['present'],
                               patterns['payment_requests']['present'],
                               patterns['vague_language']['present']]):
                        st.success("✅ No suspicious patterns detected")

    elif analyze_button:
        st.warning("⚠️ Please enter a job posting to analyze")

    # Footer
    st.markdown("---")
    st.markdown("""
        <div style="text-align: center; color: #666;">
            <p>Built with Streamlit | Models: Naive Bayes + LSTM | Interpretability: SHAP + LIME</p>
            <p>Advanced Machine Learning Project | University of Texas at Austin</p>
        </div>
    """, unsafe_allow_html=True)

if __name__ == "__main__":
    main()