# -*- coding: utf-8 -*-
"""utils

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tNKDUanSd3S5ZHR5pTvk68WoQVYCEZRv
"""

"""Utility functions for text processing"""

def combine_text_fields(row):
    """Combine all text fields into single string"""
    fields = [
        'title', 'location', 'company_profile', 'description',
        'requirements', 'benefits', 'required_experience',
        'required_education', 'industry', 'function'
    ]
    text_parts = []
    for field in fields:
        if pd.notna(row[field]):
            text_parts.append(str(row[field]))
    return ' '.join(text_parts) if text_parts else "unknown job"